const CONFIG = require('../config');
const { escapeHtml, resolveSeoDescription } = require('../utils/helpers');

function buildSeoHead(article) {
    const title = escapeHtml(article.title + CONFIG.TITLE_SUFFIX);
    const seoDescription = resolveSeoDescription(article, CONFIG.DEFAULT_DESCRIPTION);
    const description = escapeHtml(seoDescription);
    const imageUrl = article.coverImage || CONFIG.DEFAULT_OG_IMAGE;
    const url = `${CONFIG.SITE_URL}/${article.slug}`;

    return `
        <!-- Dynamic SEO Tags Generated by SSR -->
        <meta name="google-site-verification" content="hCfJiIHx9r5Wy0vuxkLKxQmqQXLYvtHV9CM2v6I6syA" />
        <title>${title}</title>
        <meta name="description" content="${description}" />
        <link rel="canonical" href="${url}" />
        
        <!-- Open Graph / Facebook / Zalo -->
        <meta property="og:site_name" content="Sống Khỏe Mỗi Ngày 24h" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="${url}" />
        <meta property="og:title" content="${title}" />
        <meta property="og:description" content="${description}" />
        <meta property="og:image" content="${imageUrl}" />
        <meta property="article:published_time" content="${article.dates.published}" />
        <meta property="article:modified_time" content="${article.dates.modified}" />
        <meta property="article:author" content="Ban Biên tập Sống Khỏe Mỗi Ngày" />
        <meta property="article:section" content="${escapeHtml(article.category.name)}" />
        
        <!-- Twitter -->
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:url" content="${url}" />
        <meta name="twitter:title" content="${title}" />
        <meta name="twitter:description" content="${description}" />
        <meta name="twitter:image" content="${imageUrl}" />
        <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
    `;
}

module.exports = {
    buildSeoHead
};
