const CONFIG = require('../config');
const { escapeHtml } = require('../utils/helpers');

function buildSeoHead(article) {
    const title = escapeHtml(article.title + CONFIG.TITLE_SUFFIX);
    const description = escapeHtml(article.excerpt || CONFIG.DEFAULT_DESCRIPTION);
    const imageUrl = article.coverImage || CONFIG.DEFAULT_OG_IMAGE;
    const url = `${CONFIG.SITE_URL}/${article.slug}`;

    return `
        <!-- Dynamic SEO Tags Generated by SSR -->
        <title>${title}</title>
        <meta name="description" content="${description}" />
        <link rel="canonical" href="${url}" />
        
        <!-- Open Graph / Facebook / Zalo -->
        <meta property="og:type" content="article" />
        <meta property="og:url" content="${url}" />
        <meta property="og:title" content="${title}" />
        <meta property="og:description" content="${description}" />
        <meta property="og:image" content="${imageUrl}" />
        <meta property="article:published_time" content="${article.dates.published}" />
        <meta property="article:modified_time" content="${article.dates.modified}" />
        <meta property="article:author" content="${escapeHtml(article.authorName)}" />
        <meta property="article:section" content="${escapeHtml(article.category.name)}" />
        
        <!-- Twitter -->
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="${url}" />
        <meta property="twitter:title" content="${title}" />
        <meta property="twitter:description" content="${description}" />
        <meta property="twitter:image" content="${imageUrl}" />
        <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
    `;
}

module.exports = {
    buildSeoHead
};
